[tool.poetry]
name = "fastapi-app"
version = "0.1.0"
description = ""
authors = ["caerulescens <caerulescens.github@proton.me>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.11"
gunicorn = "^21.2.0"
uvicorn = {extras = ["standard"], version = "^0.23.2"}
uvloop = "^0.17.0"
fastapi = "^0.103.1"
fastapi-users = {extras = ["sqlalchemy"], version = "^12.1.2"}
pydantic = "^2.3.0"
pydantic-settings = "^2.0.3"
alembic = "^1.12.0"
sqlalchemy = "^2.0.21"
asyncpg = "^0.28.0"
structlog = "^23.1.0"
starlette-prometheus = "^0.9.0"
starlette-zipkin = "^0.3.0"
asgi-correlation-id = "^4.2.0"
python-rapidjson = "^1.11"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
pytest-asyncio = "^0.21.1"
coverage = {extras = ["toml"], version = "^7.3.1"}
ruff = "^0.0.290"
sphinx = "^7.2.6"
cython = "^3.0.2"
pre-commit = "^3.4.0"

[tool.pytest.ini_options]
minversion = "7.1.1"
addopts = "-ra -q"
asyncio_mode = "auto"
testpaths = [
    "tests",
]

[tool.ruff]
target-version = "py311"
select = ["E", "F", "I"]
ignore = []

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
